#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.

set -e

autoreconf -i --force
rm -rf autom4te.cache

# Generate manual pages.
version=`grep '^C TAP Harness' NEWS | head -1 | cut -d' ' -f4`
pod2man --release="$version" --center="C TAP Harness" docs/runtests.pod \
    > docs/runtests.1
