#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.

set -e

autoreconf -i --force
rm -rf autom4te.cache

# Generate manual pages.
version=`grep '^C TAP Harness' NEWS | head -1 | cut -d' ' -f4`
pod2man --release="$version" --center="C TAP Harness" docs/runtests.pod \
    > docs/runtests.1
for doc in bail diag is_int ok plan skip skip_all ; do
    pod2man --release="$version" --center="C TAP Harness Library" \
        --section=3 --name=`echo "$doc" | tr a-z A-Z` docs/api/"$doc".pod \
        > docs/api/"$doc".3
done
