#! /bin/sh
# $Id$
#
# mkdepend -- Generate dependencies for makefiles.
#
# Copyright 2000 Russ Allbery <rra@stanford.edu>
# This work is hereby placed in the public domain by its author.
#
# Update dependencies in a Makefile or Makefile.in using gcc -MM.  This
# guarantees good results at the cost of requiring gcc, but only
# maintainers should need to run this program anyway and gcc -MM is much
# more reliable than most alternatives.  Takes compiler flags as the first
# argument and then a list of all source files to process.
#
# The Makefile is updated in place, and everything after "DO NOT DELETE
# THIS LINE" is removed and replaced by the dependencies.

if [ -f Makefile.in ] ; then
    makefile=Makefile.in
else
    makefile=Makefile
fi
sed '1,/DO NOT DELETE THIS LINE/!d' < $makefile > .makefile.tmp
flags="-MM $1"
shift
for file in `echo "$@" | sed 's%\./%%g'` ; do
    dir=`dirname $file`
    gcc $flags "$file" | sed "s%^%$dir/%" >> .makefile.tmp
    if [ $? != 0 ] ; then
        break
    fi
done
if [ $? = 0 ] ; then
    mv -f .makefile.tmp $makefile
else
    rm .makefile.tmp
fi
