#! /bin/sh
# $Id$
#
# mkusage -- Generate usage.c from from USAGE.
#
# Copyright 2000 Russ Allbery <rra@stanford.edu>
#
# This program is free software under an MIT-style license.  See the file
# LICENSE which should have accompanied this file for exact terms and
# conditions.

echo '/* Generated automatically from USAGE by mkusage. */' > usage.c
echo '' >> usage.c
echo 'static const char usage_message[] =' >> usage.c
sed -e '1s/^/\"/' -e 's/$/\\n\\/' -e '$s/\\$/\";/' < USAGE >> usage.c
cat >> usage.c <<__EOC__

#include <stdio.h>
#include <stdlib.h>

void
usage(int status)
{
    fprintf(status ? stderr : stdout, usage_message);
    exit(status);
}
__EOC__
