#! /bin/sh
#
# Test of the libtap.sh bail function
#
# Copyright 2009 Russ Allbery <eagle@eyrie.org>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/tap/libtap.sh"

plan 2
ok "" true
bail Some error message
ok "" true
exit 0
