#! /bin/sh
#
# Test of the libtap.sh end summary with extra tests and a plan of 1
#
# Copyright 2009 Russ Allbery <rra@stanford.edu>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/tap/libtap.sh"

plan 1
ok "first" true
ok "second" true
ok "third" true
exit 0
