#! /bin/sh
#
# Test of the libtap.sh end summary with extra tests
#
# Copyright 2009 Russ Allbery <rra@stanford.edu>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/tap/libtap.sh"

plan 2
ok "first" true
ok "second" false
ok "third" true
exit 0
