#!/bin/sh
#
# Test of the test_file_path utility function in libtap.sh.
#
# Copyright 2010, 2012 Russ Allbery <rra@stanford.edu>
#
# See LICENSE for licensing terms.

. "${SOURCE}/tap/libtap.sh"

echo "Path to c-file: ${BUILD}/libtap/basic/c-file" > sh-file.output
echo "Path to c-basic.output: ${SOURCE}/libtap/basic/c-basic.output" \
    >> sh-file.output
echo "Path to c-file: " >> sh-file.output
echo "Path to c-basic.output: " >> sh-file.output
path=`test_file_path 'libtap/basic/c-file'`
echo "Path to c-file: $path"
path=`test_file_path 'libtap/basic/c-basic.output'`
echo "Path to c-basic.output: $path"
BUILD=
SOURCE=
path=`test_file_path 'libtap/basic/c-file'`
echo "Path to c-file: $path"
path=`test_file_path 'libtap/basic/c-basic.output'`
echo "Path to c-basic.output: $path"
exit 0
