#! /bin/sh
#
# Test of lazy planning with libtap.sh.
#
# Copyright 2010, 2016 Russ Allbery <eagle@eyrie.org>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$C_TAP_SOURCE/tap/libtap.sh"

plan_lazy
ok "first" true
skip "second"
exit 0
