#! /bin/sh
#
# Test of the libtap.sh end summary with missing tests and a plan of 1
#
# Copyright 2009, 2016 Russ Allbery <eagle@eyrie.org>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$C_TAP_SOURCE/tap/libtap.sh"

plan 1
exit 0
