#! /bin/sh
#
# Test of the libtap.sh skip_all function
#
# Copyright 2009 Russ Allbery <eagle@eyrie.org>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/tap/libtap.sh"

skip_all "some reason"
ok true
exit 1
