#! /bin/sh
#
# Test of the libtap.sh end summary with all successful tests
#
# Copyright 2009, 2016 Russ Allbery <eagle@eyrie.org>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$C_TAP_SOURCE/tap/libtap.sh"

plan 2
ok "first" true
skip "second"
exit 0
