#!/bin/sh
#
# Test of the test_tmpdir utility function in libtap.sh.
#
# Copyright 2009, 2012, 2016 Russ Allbery <eagle@eyrie.org>
#
# See LICENSE for licensing terms.

. "${C_TAP_SOURCE}/tap/libtap.sh"

set -e
echo "Path to temporary directory: ${C_TAP_BUILD}/tmp" > sh-tmpdir.output
if [ -e "${C_TAP_BUILD}/tmp" ] ; then
    bail "${C_TAP_BUILD}/tmp already exists"
fi
path=`test_tmpdir`
echo "Path to temporary directory: $path"
if [ ! -d "${C_TAP_BUILD}/tmp" ] ; then
    bail "${C_TAP_BUILD}/tmp not created"
fi
rmdir "${C_TAP_BUILD}/tmp"
exit 0
