#! /bin/sh
#
# Test of the libtap.sh diag function.
#
# Copyright 2010 Russ Allbery <rra@stanford.edu>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/../tap/libtap.sh"

plan 1
diag 'foo'
ok 'first test' true
diag 'bar baz foo'
exit 0
