#! /bin/sh
#
# Test of lazy planning with libtap.sh.
#
# Copyright 2010 Russ Allbery <rra@stanford.edu>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/../tap/libtap.sh"

plan_lazy
ok "first" true
skip "second"
exit 0
