#! /bin/sh
#
# Test of the libtap.sh end summary with missing tests and a plan of 1
#
# Copyright 2009 Russ Allbery <rra@stanford.edu>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/../tap/libtap.sh"

plan 1
exit 0
