#! /bin/sh
#
# Test of the libtap.sh end summary with missing tests
#
# Copyright 2009 Russ Allbery <rra@stanford.edu>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/../tap/libtap.sh"

plan 2
ok "first" false
exit 0
