#! /bin/sh
#
# Test of the libtap.sh skip_all function
#
# Copyright 2009 Russ Allbery <rra@stanford.edu>
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/../tap/libtap.sh"

skip_all "some reason"
ok true
exit 1
