#!/bin/sh
. "${SOURCE}/../tap/libtap.sh"

set -e
echo "Path to temporary directory: ${BUILD}/tmp" > sh-tmpdir.output
if [ -e "${BUILD}/tmp" ] ; then
    bail "${BUILD}/tmp already exists"
fi
path=`test_tmpdir`
echo "Path to temporary directory: $path"
if [ ! -d "${BUILD}/tmp" ] ; then
    bail "${BUILD}/tmp not created"
fi
rmdir "${BUILD}/tmp"
exit 0
